language: node_js
node_js:
- '10'
sudo: required
before_install:
- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn
cache:
  yarn: true
install:
- yarn install
script:
- yarn test
- yarn prepublishOnly
deploy:
  provider: npm
  skip_cleanup: true
  api_key:
    secure: BrvR5xc+J+orKCFHMnmhsbar+jG6+pwBVp76YDEUYXpLPRBKxCa7MA0eTUKHtCBMcrn3DqklYkFRXlWO/HD+pgHL0pioKdri5tJFo3DncSeWXkvzA4XP7zdyF6Upvd44v3FMNPiY3e5dspN+qCfBm4IHCOYgwoYhmDI1xssVWeEvBFFQ/vEyATSdsItyTOSIxc/JY7OpX/BX8odSkFnF9VnXVH9Dz7aKSewlkOcmimjgLmSTZK+H4kEOiaAHWhba8TJ4U48N/KbQjQjzp5ZZJjwCchrTVgAr3l6NyDS+Qra4+gZFe5bO8gzixDjeNVG/x/nuZl7/5F1CA6F/tg0Xa7sJ/dpvLKPBpJ7Z8eMmFwGCMnI3GKg8yprO32bDrEc08TrrF7tmytvM/FCTa1L0u+0AAnGx4iblNaOp8MbdzU83Pya1rnNmDug4dWLpLekiRc3yDhX6fTC+z2q8C75SlM/loSBZsKEhfTS59Y8gYQC6WCwdLnKUL+Kfr2RGmGu02ME/IKb0uNBA8Zgj0KKth9oEaOZ9BWCbl9W8vq67xUrGVMfkiwLrqdCRLcD7sh1xpduDXJ+FiuFeiijGc75cYhdhLYqPRjCJsxWizWyPibzsSgDsUJFDcCSS8xooCR9VBltsKqnZmg+dZEz+lrk6pyaYg3GRNjImS9zIyTEOTtA=
  email:
    secure: EArOiWnjdPv2fZKCvoEptb2q46Np/Mwb/KycsJGjPS5J/ecWyQEjnKUibhOqPjK1IuFzZSP9vls9T332SNthdo4oYqEaOnfWnbbIS6Epy79zmvowy7j61DuDpcNw8IuI6ZsfcCSzvO/StSCQb2+6H8/nP+EGtPUS0o3azIG4S2cmjdH0286rchQc9WszOLoz1M/Mw8FJlOvqjdorqo7ND9dj+o/gC2FKnwhCaNdpJu3Cyo49+YbjfhMB1V3WFMzp4wKlD5gpTYSdbgkQg/WSJtKDA/wwundH8zCyw28HhFWBCP5QUayNdDOsOOlqAZdDV9d/IeMS/BIgXcUve3HljKuflWjShDUDtkmojKrq2F4WG9/Z60zbD7D1CPK3tmLMqwZOMQ/io0/8MBlfj7xGgi0OnCgZjMh9wJL4c4WDrr+B9lX3MUUQLGbyMEXgJj2IaP9bTcaxkDwys41KFZqfhs79ypVBvAyrK+//kabSw4UD72m9i43x/9tZHepFvu0vpazQQp/IRH2LTqdanFrzy7TYn+2qEtb0HB4z/WPxIaUx82NADd/IAa9FNJo6tLp7cHZSI2cVPNKx7jm5k8wxv/cRfNtM2j4oncSZLG+BxG61sGn4xhuga8eo3A6wpYdMMClNbvCTNNFAx4UJzXpXMHD+w7Jw4XXbqs0jAUDdlb4=
  on:
    branch: master
notifications:
  recipients:
  - giespaepen@outlook.com
  email:
    on_success: always
    on_failure: always
  on:
    branch: master
